[phases.setup]
nixPkgs = ["nodejs-18_x", "python312"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "cd desktop && npm install",
  "cd desktop && npm run build:react"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd api && python app.py"

